import type { FormConfig, FormField, FormStep } from "./types";
import type { InternalUploadService } from "~/src/components/utils/upload/types";

interface FormConfigOptions {
  uploadService?: InternalUploadService;
}

const createBasicInfoFields = (): FormField[] => [
  {
    id: "title",
    name: "title",
    label: "Título do Produto",
    hint: "Nome completo do produto",
    type: "text",
    required: true,
    placeholder: "Ex: Camiseta Básica Preta",
    gridCols: 12,
  },
  {
    id: "description",
    name: "description",
    label: "Descrição",
    hint: "Descrição detalhada do produto",
    type: "textarea",
    required: false,
    placeholder: "Descreva o produto...",
    gridCols: 12,
  },
  {
    id: "sku",
    name: "sku",
    label: "SKU",
    hint: "Código SKU do produto",
    type: "text",
    required: false,
    placeholder: "Ex: PROD-001",
    gridCols: 6,
  },
  {
    id: "status",
    name: "status",
    label: "Status",
    hint: "Status do produto",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
      { value: "active", label: "Ativo" },
      { value: "inactive", label: "Inativo" },
      { value: "draft", label: "Rascunho" },
    ],
    gridCols: 6,
  },
  {
    id: "category_name",
    name: "category_name",
    label: "Categoria",
    hint: "Categoria do produto",
    type: "text",
    required: true,
    placeholder: "Ex: Cervejas",
    gridCols: 6,
  },
  {
    id: "unity_type",
    name: "unity_type",
    label: "Tipo de Unidade",
    hint: "Tipo de unidade de medida",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
      { value: "UNITY", label: "Unidade" },
      { value: "KG", label: "Quilograma" },
      { value: "L", label: "Litro" },
      { value: "M", label: "Metro" },
    ],
    defaultValue: "UNITY",
    gridCols: 6,
  },
  {
    id: "product_origin",
    name: "product_origin",
    label: "Origem do Produto",
    hint: "Origem do produto",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
      { value: "NATIONAL", label: "Nacional" },
      { value: "IMPORTED", label: "Importado" },
    ],
    defaultValue: "NATIONAL",
    gridCols: 6,
  },
  {
    id: "marketing_type",
    name: "marketing_type",
    label: "Tipo de Comercialização",
    hint: "Tipo de comercialização",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
      { value: "RESALE", label: "Revenda" },
      { value: "PRODUCTION", label: "Produção Própria" },
    ],
    defaultValue: "RESALE",
    gridCols: 6,
  },
  {
    id: "stock_handling",
    name: "stock_handling",
    label: "Controle de Estoque",
    hint: "Ativar controle de estoque",
    type: "checkbox",
    required: false,
    defaultValue: true,
    gridCols: 12,
  },
];

const createImagesFields = (uploadService?: InternalUploadService): FormField[] => {
  if (!uploadService) {
    return [];
  }

  return [
    {
      id: "images_product",
      name: "images.product",
      label: "Imagens do Produto",
      hint: "Adicione até 8 imagens principais do produto",
      type: "upload",
      required: false,
      uploadConfig: {
        typeImport: "internal",
        service: uploadService,
        maxFiles: 8,
        accept: "image/*",
        emptyStateLabel: "Arraste e solte ou clique para selecionar imagens do produto",
        uploadType: "product",
      },
      gridCols: 12,
    },
  ];
};

const createPriceStockFields = (): FormField[] => [
  {
    id: "price_cost",
    name: "price_cost",
    label: "Preço de Custo",
    hint: "Preço de compra do produto",
    type: "number",
    required: true,
    placeholder: "0.00",
    prefix: "R$",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "price_sale",
    name: "price_sale",
    label: "Preço de Venda",
    hint: "Preço de venda do produto",
    type: "number",
    required: true,
    placeholder: "0.00",
    prefix: "R$",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "available_quantity",
    name: "available_quantity",
    label: "Quantidade Disponível",
    hint: "Quantidade em estoque",
    type: "number",
    required: true,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "initial_quantity",
    name: "initial_quantity",
    label: "Quantidade Inicial",
    hint: "Quantidade inicial em estoque (modo completo)",
    type: "number",
    required: false,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
    conditional: {
      field: "registration_type",
      operator: "equals",
      value: "complete",
    },
  },
  {
    id: "minimum_quantity",
    name: "minimum_quantity",
    label: "Quantidade Mínima",
    hint: "Quantidade mínima em estoque",
    type: "number",
    required: false,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "maximum_quantity",
    name: "maximum_quantity",
    label: "Quantidade Máxima",
    hint: "Quantidade máxima em estoque",
    type: "number",
    required: false,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
];

const createGeneralDataFields = (): FormField[] => [
  {
    id: "product_name",
    name: "product_name",
    label: "Nome do Produto",
    hint: "Nome completo do produto",
    type: "text",
    required: true,
    placeholder: "Descrição do Produto",
    gridCols: 12,
  },
  {
    id: "sku_general",
    name: "sku_general",
    label: "SKU",
    hint: "Código de identificação",
    type: "text",
    required: false,
    placeholder: "Código de identificação",
    gridCols: 6,
  },
  {
    id: "model",
    name: "model",
    label: "Modelo",
    hint: "Código de identificação",
    type: "text",
    required: false,
    placeholder: "Código de identificação",
    gridCols: 6,
  },
  {
    id: "brand",
    name: "brand",
    label: "Marca",
    hint: "Marca do produto",
    type: "text",
    required: true,
    placeholder: "Marca do produto",
    gridCols: 6,
  },
  {
    id: "type",
    name: "type",
    label: "Tipo",
    hint: "Tipo do produto",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
    ],
    gridCols: 6,
  },
  {
    id: "origin",
    name: "origin",
    label: "Origem",
    hint: "Origem do produto",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
      { value: "NATIONAL", label: "Nacional" },
      { value: "IMPORTED", label: "Importado" },
    ],
    gridCols: 6,
  },
  {
    id: "gtin_ean",
    name: "gtin_ean",
    label: "GTIN/EAN",
    hint: "Código de barras",
    type: "text",
    required: true,
    placeholder: "Código de barras",
    gridCols: 6,
  },
  {
    id: "ncm_general",
    name: "ncm_general",
    label: "NCM",
    hint: "Código NCM",
    type: "text",
    required: true,
    placeholder: "(Ex: 1001.10.10)",
    gridCols: 6,
  },
  {
    id: "cest_general",
    name: "cest_general",
    label: "CEST",
    hint: "Código CEST",
    type: "text",
    required: true,
    placeholder: "(Ex: 01.003.00)",
    gridCols: 6,
  },
  {
    id: "invoice_value",
    name: "invoice_value",
    label: "Valor da Nota",
    hint: "Valor da nota fiscal",
    type: "number",
    required: true,
    placeholder: "0.00",
    prefix: "R$",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
];

const createDimensionsFields = (): FormField[] => [
  {
    id: "unit_type",
    name: "unit_type",
    label: "Unidade",
    hint: "Tipo de unidade de medida",
    type: "toggle",
    required: true,
    toggleOptions: {
      left: "Milímetros",
      right: "Centímetros",
    },
    defaultValue: "Centímetros",
    gridCols: 12,
  },
  {
    id: "width",
    name: "width",
    label: "Largura",
    hint: "Largura do produto",
    type: "number",
    required: true,
    placeholder: "0",
    suffix: "cm",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "height",
    name: "height",
    label: "Altura",
    hint: "Altura do produto",
    type: "number",
    required: true,
    placeholder: "0",
    suffix: "cm",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "depth",
    name: "depth",
    label: "Comprimento",
    hint: "Comprimento do produto",
    type: "slider",
    required: true,
    sliderConfig: {
      min: 0,
      max: 3200,
      step: 1,
      unit: "cm",
    },
    gridCols: 12,
  },
  {
    id: "brute_weight",
    name: "brute_weight",
    label: "Peso bruto",
    hint: "Peso bruto do produto",
    type: "text",
    required: true,
    placeholder: "Ex: 400G",
    gridCols: 6,
  },
  {
    id: "volumes",
    name: "volumes",
    label: "Número de Volumes",
    hint: "Quantidade de volumes",
    type: "number",
    required: true,
    placeholder: "0",
    suffix: "Unidades",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "packaging_type",
    name: "packaging_type",
    label: "Tipo de Embalagem",
    hint: "Tipo de embalagem do produto",
    type: "select",
    required: false,
    options: [
      { value: "", label: "Selecione" },
      { value: "PACKAGE", label: "Pacote/Caixa" },
      { value: "ENVELOPE", label: "Envelope" },
      { value: "OTHER", label: "Outro" },
    ],
    gridCols: 6,
  },
  {
    id: "packaging_custom",
    name: "packaging_custom",
    label: "Embalagem",
    hint: "Embalagem customizada",
    type: "text",
    required: false,
    placeholder: "Customizada",
    gridCols: 6,
  },
  {
    id: "stock_quantity",
    name: "stock_quantity",
    label: "Estoque",
    hint: "Quantidade em estoque",
    type: "number",
    required: true,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "min_stock",
    name: "min_stock",
    label: "Estoque Mín",
    hint: "Estoque mínimo",
    type: "number",
    required: false,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "max_stock",
    name: "max_stock",
    label: "Estoque Máx",
    hint: "Estoque máximo",
    type: "number",
    required: false,
    placeholder: "0",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "location",
    name: "location",
    label: "Localização",
    hint: "Localização do produto no estoque",
    type: "text",
    required: false,
    placeholder: "Ex: Corredor 1",
    gridCols: 6,
  },
  {
    id: "preparation_days",
    name: "preparation_days",
    label: "Dias Para Preparação",
    hint: "Dias necessários para preparação",
    type: "text",
    required: false,
    placeholder: "Ex: 3d",
    gridCols: 6,
  },
  {
    id: "supplier",
    name: "supplier",
    label: "Fornecedor",
    hint: "Fornecedor do produto",
    type: "select",
    required: true,
    options: [
      { value: "", label: "Selecione" },
    ],
    gridCols: 6,
  },
];

const createAdditionalCostFields = (): FormField[] => [
  {
    id: "acquisition_cost",
    name: "acquisition_cost",
    label: "Custo de Aquisição",
    hint: "Preço pago ao fornecedor",
    type: "number",
    required: true,
    placeholder: "Preço pago ao fornecedor",
    prefix: "R$",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "logistics_cost",
    name: "logistics_cost",
    label: "Custo de Logística",
    hint: "(Ex: Frete de entrada: Armazenagem)",
    type: "text",
    required: false,
    placeholder: "(Ex: Frete de entrada: Armazenagem)",
    gridCols: 6,
  },
  {
    id: "packaging_cost",
    name: "packaging_cost",
    label: "Custos de Embalagem",
    hint: "Custo de embalagem do produto",
    type: "number",
    required: false,
    placeholder: "0.00",
    prefix: "R$",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "marketplace_fees",
    name: "marketplace_fees",
    label: "Taxas de Marketplace",
    hint: "Taxas cobradas pela plataforma",
    type: "number",
    required: false,
    placeholder: "0",
    suffix: "%",
    validation: {
      min: 0,
      max: 100,
    },
    gridCols: 6,
  },
  {
    id: "tax_rate",
    name: "tax_rate",
    label: "Alíquotas (impostos diretos)",
    hint: "Taxa de impostos diretos",
    type: "number",
    required: false,
    placeholder: "0",
    suffix: "%",
    validation: {
      min: 0,
      max: 100,
    },
    gridCols: 6,
  },
  {
    id: "extra_cost",
    name: "extra_cost",
    label: "Custos Adicionais",
    hint: "Custos adicionais do produto",
    type: "number",
    required: false,
    placeholder: "0.00",
    prefix: "R$",
    validation: {
      min: 0,
    },
    gridCols: 6,
  },
  {
    id: "desired_margin",
    name: "desired_margin",
    label: "Margem Desejada",
    hint: "Margem de lucro desejada",
    type: "number",
    required: false,
    placeholder: "0",
    suffix: "%",
    validation: {
      min: 0,
      max: 100,
    },
    gridCols: 6,
  },
  {
    id: "suggested_price",
    name: "suggested_price",
    label: "Preço Sugerido",
    hint: "Preço sugerido calculado automaticamente",
    type: "number",
    required: false,
    placeholder: "0.00",
    prefix: "R$",
    disabled: true,
    gridCols: 6,
  },
];

const createVariationsFields = (): FormField[] => [
  {
    id: "has_variations",
    name: "has_variations",
    label: "Produto possui variações?",
    hint: "Marque se o produto possui variações (tamanho, cor, etc.)",
    type: "checkbox",
    required: false,
    gridCols: 12,
  },
];

const createSimplifiedSteps = (uploadService?: InternalUploadService): FormStep[] => [
  {
    id: "basic_info",
    label: "Informações Básicas",
    description: "Dados principais do produto",
    fields: createBasicInfoFields(),
    validateBeforeNext: true,
    icon: "document",
  },
  {
    id: "images",
    label: "Imagens",
    description: "Adicione as imagens do seu produto. Você pode adicionar até 8 imagens principais que serão usadas nos anúncios e na apresentação do produto.",
    fields: createImagesFields(uploadService),
    optional: true,
    icon: "eye",
  },
  {
    id: "variations_check",
    label: "Variações",
    description: "Informe se o produto possui variações",
    fields: createVariationsFields(),
    optional: true,
    icon: "list",
  },
  {
    id: "variations",
    label: "Cadastro de Variações",
    description: "Configure as variações do produto",
    fields: [],
    optional: true,
    conditional: {
      condition: {
        field: "has_variations",
        operator: "equals",
        value: true,
      },
    },
    icon: "list",
  },
  {
    id: "price_stock",
    label: "Preços e Estoque",
    description: "Defina preços e quantidade em estoque",
    fields: createPriceStockFields(),
    validateBeforeNext: true,
    icon: "currency_dollar",
  },
];

const createCompleteSteps = (uploadService?: InternalUploadService): FormStep[] => [
  {
    id: "variations",
    label: "Variações",
    description: "Preencha os campos necessários para cadastrar seu produto, incluindo informações de estoque, dimensões, dados fiscais e identificação. Esses dados são fundamentais para facilitar a criação de anúncios no futuro.",
    fields: createVariationsFields(),
    optional: true,
    icon: "list",
  },
  {
    id: "general_data",
    label: "Dados Gerais",
    description: "Preencha os campos necessários para cadastrar seu produto, incluindo informações de estoque, dimensões, dados fiscais e identificação. Esses dados são fundamentais para facilitar a criação de anúncios no futuro.",
    fields: createGeneralDataFields(),
    validateBeforeNext: true,
    icon: "document",
  },
  {
    id: "financial",
    label: "Financeiro",
    description: "Adicione os principais custos relacionados ao produto, como aquisição, logística, taxas de plataforma, embalagens e alíquota. Aqui, todos os dados são calculados para ajudar você a definir a precificação ideal e maximizar sua lucratividade.",
    fields: createAdditionalCostFields(),
    optional: true,
    icon: "currency_dollar",
  },
  {
    id: "size_stock",
    label: "Tamanho e Estoque",
    description: "Informe as dimensões e controle de estoque do produto. Essas informações são essenciais para o gerenciamento de inventário e para criar anúncios precisos.",
    fields: createDimensionsFields(),
    optional: true,
    icon: "box",
  },
  {
    id: "additional_details",
    label: "Detalhes Adicionais",
    description: "Complete os dados complementares do produto, como descrição detalhada, categoria, fotos e vídeos. Essas informações aprimoram a apresentação do item em seus anúncios e ajudam a atrair clientes.",
    fields: [
      ...createImagesFields(uploadService),
      {
        id: "categories",
        name: "categories",
        label: "Categorias",
        hint: "Selecione a categoria do seu produto",
        type: "category-cards",
        required: true,
        categoryOptions: [],
        gridCols: 12,
      },
      {
        id: "product_documentation",
        name: "product_documentation",
        label: "Documentação sobre o produto",
        hint: "Descrição detalhada do produto",
        type: "rich-text",
        required: true,
        placeholder: "Escreva algo aqui",
        gridCols: 12,
      },
      {
        id: "ai_integrated",
        name: "ai_integrated",
        label: "IA Integrada",
        hint: "Geração de texto com IA",
        type: "rich-text",
        required: false,
        placeholder: "Escreva algo aqui",
        gridCols: 12,
      },
      {
        id: "support_video",
        name: "support_video",
        label: "Vídeo de Apoio",
        hint: "Link do vídeo do YouTube",
        type: "text",
        required: false,
        placeholder: "Insira o Link do Vídeo no Youtube Aqui...",
        gridCols: 12,
      },
    ],
    optional: true,
    icon: "eye",
  },
  {
    id: "ads",
    label: "Anúncios",
    description: "Integre seu produto com anúncios ou crie novos anúncios diretamente. Os dados do produto serão pré-preenchidos, facilitando a criação e finalização rápida dos anúncios.",
    fields: [],
    optional: true,
    icon: "megaphone",
  },
];

export const getFormConfig = (
  mode: "simplificado" | "completo",
  options?: FormConfigOptions
): FormConfig => {
  const uploadService = options?.uploadService;
  const steps =
    mode === "simplificado"
      ? createSimplifiedSteps(uploadService)
      : createCompleteSteps(uploadService);

  return {
    mode,
    steps,
    validateOnChange: true,
  };
};

